#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidPager.Resource", IsApplication=true)]

namespace AndroidPager
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int Autor = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Descripcion = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int Fecha = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int Titulo = 2131034113;
			
			// aapt resource value: 0x7f05001c
			public const int btnIngresar = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int btnRegistrar = 2131034137;
			
			// aapt resource value: 0x7f05001f
			public const int checkedTextView1 = 2131034143;
			
			// aapt resource value: 0x7f050015
			public const int edtDescrip = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int edtEmail = 2131034136;
			
			// aapt resource value: 0x7f050013
			public const int edtEstatura = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int edtFecha_nac = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int edtId = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int edtPass = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int edtPerfil = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int edtPeso = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int edtPosicion = 2131034132;
			
			// aapt resource value: 0x7f05001b
			public const int edtUser = 2131034139;
			
			// aapt resource value: 0x7f050007
			public const int imgPerfil = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout2 = 2131034121;
			
			// aapt resource value: 0x7f05001d
			public const int linearLayout3 = 2131034141;
			
			// aapt resource value: 0x7f050006
			public const int listView1 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int pager = 2131034117;
			
			// aapt resource value: 0x7f050020
			public const int progressBar1 = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int radioButton1 = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int textView1 = 2131034138;
			
			// aapt resource value: 0x7f05000a
			public const int textView2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView3 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int textView4 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int textView5 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textView6 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int textView7 = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int txtNombre = 2131034120;
			
			// aapt resource value: 0x7f05001e
			public const int txtText = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Control = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Noticias = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Perfil = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int registro = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Sesion = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int tab = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int test = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
